### PR TITLE
Add MCP73831/MCP73832 battery charge ICs

### PR DESCRIPTION
**Pull request by dbrgn**
##### SUMMARY

These are two simple, cheap and widely used Li-Ion/Li-Po battery charging ICs.

Example application: Adafruit LiPo chargers https://learn.adafruit.com/adafruit-microlipo-and-minilipo-battery-chargers/overview

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/MCP73831-Family-Data-Sheet-DS20001984H.pdf

The difference between the two is the status output: The 73831 status output can directly drive LEDs, while the 73832 status output is open drain.

The "typical application" circuit replicated in LibrePCB:

ex

##### OPEN QUESTIONS / UNRESOLVED ISSUES

- If the status output of the two is electrically different, should there be two separate components?

##### CHECKLIST

- [x] I have read and followed the [library conventions](https://docs.librepcb.org/#libraryconventions).
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the [CC0 Public Domain License](https://en.wikipedia.org/wiki/CC0), allowing everyone to use and modify the content without any restrictions.

### CODE REVIEW

**Comment by dbrgn** [comment]
The two DFN package variants could be added as well, but that depends on the resolution of #17.

**Comment by ubruhin** [comment]
Generally everything looks good, but

> If the status output of the two is electrically different, should there be two separate components?

I'd say yes since this is an important difference for the ERC. Although not yet fully supported by LibrePCB, I'd recommend to have separate components to avoid issues once LibrePCB supports to distinguish between push-pull and open-drain outputs.

**Comment by ubruhin** [comment]
@dbrgn I wanted to quickly apply the separation of the components (see discussion above; commits already pushed) but when I started to update the devices accordingly, I realized that there are actually a lot of different MPNs available for different battery voltages. Some time ago we decided to generally make separate devices for different MPNs and I think especially for this device this really makes sense since it is important to use the correct MPN (due to different electrical function). So I'd suggest to change the device name to the full MPN (just without the "T" for tape&reel).

Now the only questions are: Do you agree on this rename? And which exact MPN did you need when creating this PR (to allow re-using the current UUID without breaking your project)?

**Comment by dbrgn** [comment]
> So I'd suggest to change the device name to the full MPN (just without the "T" for tape&reel).

Yeah, probably makes sense.

> And which exact MPN did you need when creating this PR (to allow re-using the current UUID without breaking your project)?

I don't remember what project I used this with 😄 Adafruit seems to use the code KD4E according to [this picture](https://paradisetronic.com/media/images/org/1904-06.jpg). That corresponds to the MPN `MCP73831T-2ACI/OT`.

**Comment by ubruhin** [comment]
Alright, renamed the device to "MCP73831T-2ACI/OT" (including "T" since "/OT" variants seem to be available only with tape&reel)!

**Pull request merged**
