### PR TITLE
Add ATmega32A

### PR DESCRIPTION
**Pull request by ianliu**
##### SUMMARY

I have added the ATmega32A-PU microcontroller from Microchip. The PR has

 * a Symbol and a Component called ATmega32A;
 * a device called ATmega32A-PUPx with the 40 pin DIP package.

##### CHECKLIST

- [x] I have read and followed the [library conventions](https://docs.librepcb.org/#libraryconventions).
- [x] For packages, I followed IPC7351C (see details in library conventions). *No packages were created*
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the [CC0 Public Domain License](https://en.wikipedia.org/wiki/CC0), allowing everyone to use and modify the content without any restrictions.

### CODE REVIEW

**Comment by ubruhin** [comment]
Thanks @ianliu! Generally it looks very good! :smiley: 

I have only some small review comments:
- The signal RESET should be renamed to nRESET to make clear that it is inverted.
- For consistency, the pins at the left of the symbol should be aligned to the top, not somewhere in the middle (i.e. RESET should be at the same Y-coordinate as PA0).
- To make schematic design slightly more structured and for consistency with other microcontroller symbols, I'd change the order of the pins on the left of the symbol (from top to bottom): nRESET, VCC, GND, AREF, AVCC, AGND, XTAL1, XTAL2

**Comment by ubruhin** [comment]
Ah, and I almost forgot to mention that you added a symbol named "Teste", I suspect this is not intended, so it should be removed :wink:

**Comment by ianliu** [comment]
@ubruhin fixed your suggestions! Could you review?

Cheers,
Ian

**Comment by ubruhin** [comment]
Looks good, thank you very much @ianliu! :tada:

**Pull request merged**
