### PR TITLE
correct size, add PWM labels on ATtiny85

### PR DESCRIPTION
**Pull request by sanbeg**
##### SUMMARY

Fixed the flash size 8 bytes -> 8 kilobytes
Updated pin labels to include PWM info.

##### CHECKLIST

- [x] I have read and followed the [library conventions](https://docs.librepcb.org/#libraryconventions).
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the [CC0 Public Domain License](https://en.wikipedia.org/wiki/CC0), allowing everyone to use and modify the content without any restrictions.

### CODE REVIEW

**Comment by ubruhin** [comment]
Thanks @sanbeg! :smiley: 

@dbrgn Since those elements were created by you, could you maybe review this?

**Comment by dbrgn** [comment]
Haha, nice catch with the 8 bytes :slightly_smiling_face: 

Unfortunately the additional pin features cause the labels to overlap:

overlap

This is a general problem, and we don't have a good solution for it yet. It is being discussed here: https://librepcb.discourse.group/t/alternate-pin-functions/34/1

In this case, I would recommend to simply make the symbol a bit more wide. The ATtiny is simple enough that we can list all pin features in the symbol. (On more complex microcontrollers we usually omit the pin functions from the pin name.) @sanbeg could you update your pull request with that?

**Comment by dbrgn** [comment]
> In this case, I would recommend to simply make the symbol a bit more wide. The ATtiny is simple enough that we can list all pin features in the symbol.

Hm, after re-checking the datasheet, I noticed that the pin also has other functions, like CLK0 / XTAL2. So the symbol would need to be even wider if we wanted to include all functions... With that in mind, I think I would rather omit the PWM functionality from the symbol to make it more readable and to stick to the most important information only. Would this be OK for you, @sanbeg? If yes, could you update your pull request to contain only the description change? (Let me know if you need help with that, or if I should do it for you!)

**Comment by sanbeg** [comment]
Hey, sorry for the delay.
I'm adapting from the Arduino world, where the boards tend to only be labelled with a pin number and an indication of which pins have ADC and which have PWM.  So I thought it wold save some cross referencing between schematics & datasheets if the most important info was on the symbol.  Admittedly, I did omit some other info, such as complementary clock outputs, which seem less useful to me.

Would it make sense to prioritize which functions are shown?  I.e. the pin that overlaps lists an AREF function which is probably  less used than PWM.  Or would it make more sense to adopt something like the ~ notation used on some Arduino boards to mark PWMs; i.e.
`PB0~/MOSI/AREF/PCINT0`

**Comment by sanbeg** [comment]
Since my t13 PR wound up affecting the t85 anyway, I also added the change to the flash size there.

**Review by dbrgn — CHANGES_REQUESTED** [review]
Sorry @sanbeg for the long delay!

There is an ongoing discussion about a system for marking alternate pin functions: https://librepcb.discourse.group/t/alternate-pin-functions/34

Until then, I would prefer if you'd undo the pin name change, to keep only the description updates (which are already valuable).

(If you don't have time, I can also do the requested change myself and push it to your branch!)

**Comment by dbrgn** [comment]
Actually, this PR is obsolete for now, since the changes are already included in #12!

**Pull request closed without merging**
