### PR TITLE
Add PIC10F32x and PIC10F20x

### PR DESCRIPTION
**Pull request by HBadertscher**
Datasheets:

- [PIC10F20x](http://ww1.microchip.com/downloads/en/DeviceDoc/40001239F.pdf)
- [PIC10(L)F32x](http://ww1.microchip.com/downloads/en/DeviceDoc/40001585D.pdf)

Symbols:

- PIC10F20x
- PIC10(L)F32x

Components:

I had to create separate components, one for PIC10F200 and PIC10F202, and a separate one for PIC10F204 and PIC10F206 due to the different pin names / functions:

- PIC10F200/2
- PIC10F204/6
- PIC10(L)F32x

Devices:

The endings are `/MC` for DFN packages, `/P` for DIP packages, and `/OT` for SOT23-6. 

I tried to generate as few devices as possible and used placeholders: Letters in parentheses `()` are optional. `x` and `?` are two different placeholders, and with `200/2` I denote that `200` and `202` are possible. Does this make sense? Is there already a guideline on how this should be done?

Here's a full list of devices:

- PIC10F200/2-?/MC
- PIC10F200/2-?/P
- PIC10F200/2(T)-?/OT
- PIC10F204/6-?/MC
- PIC10F204/6-?/P
- PIC10F204/6(T)-?/OT
- PIC10(L)F32x(T)-?/MC
- PIC10(L)F32x(T)-?/OT
- PIC10(L)F32x(T)-?/P

Note: the DFN package according to the datasheet has a slightly different exposed pad than the standard one I selected here, so I guess I'll need to create a custom DFN package for this PR.

### CODE REVIEW

**Comment by ubruhin** [comment]
Sorry for the delay!

Looks very good :+1: 

> I tried to generate as few devices as possible and used placeholders: Letters in parentheses `()` are optional. `x` and `?` are two different placeholders, and with `200/2` I denote that `200` and `202` are possible. Does this make sense? Is there already a guideline on how this should be done?

We don't have guidelines for that yet. So far it looks good to me, except maybe that using only one placeholder for both places would be sufficient, but I'm not sure. At least we could rename it at any time if we have a better idea ;)

> Note: the DFN package according to the datasheet has a slightly different exposed pad than the standard one I selected here, so I guess I'll need to create a custom DFN package for this PR.

Hmm yeah I think this should be fixed because it's very important to have the right package selected. I would say the package with proper exposed pad size could be added to the base library, couldn't it? As it's actually nothing Microchip-specific, the package could be re-used by other devices if other devices need the same exposed pad size.

**Comment by rnestler** [comment]
> Hmm yeah I think this should be fixed because it's very important to have the right package selected. I would say the package with proper exposed pad size could be added to the base library, couldn't it? As it's actually nothing Microchip-specific, the package could be re-used by other devices if other devices need the same exposed pad size.

Hmm? Is it Microchip specific or not? @HBadertscher ?

**Review by rnestler — COMMENTED** [review]
Devices:
 * Whats up with the question marks in the Names?
 * Did we yet agree on how to name negated functions? This uses `!MCLR`

**Comment by HBadertscher** [comment]
Thanks for the review @rnestler 

> Hmm? Is it Microchip specific or not? 

As far as I know, yes it is Microchip specific. Therefore, I added it as `Microchip DFN50P200X300X90-8T175X145` to this pull request and not to Base.

> Whats up with the question marks in the Names?

> x and ? are two different placeholders

I use `?` as the placeholder for the temperature range (either `I` for industrial, -40 .. 85 °C or `E` for extended, -40 .. 125 °C). `x` can be either `0` or `2`, so we can use it for the 10F320 and 10F322, as they are identical apart from the amount of flash.
I couldn't find any guidelines on how to handle this - are there any? Do you think this makes sense or should I rather create separate devices?

> Did we yet agree on how to name negated functions? This uses `!MCLR`

I do not know, I didn't find any guidelines on that. Any inputs @dbrgn @ubruhin?

**Comment by dbrgn** [comment]
I'd personally use `x` for all placeholders.

**Comment by ubruhin** [comment]
> As far as I know, yes it is Microchip specific. Therefore, I added it as Microchip DFN50P200X300X90-8T175X145 to this pull request and not to Base.

Sorry, I still don't understand it :grin: It looks exactly the same as the DFN packages in the Base library - it's just one additional variant with a specific exposed pad size, isn't it? If it is, it could be used by other devices/manufacturers too, so IMHO it's *not* Microchip specific...

> I couldn't find any guidelines on how to handle this - are there any? Do you think this makes sense or should I rather create separate devices?

Handling part numbers and related topics is still an open topic, thus currently there is no guideline whether separate devices or placeholders in the name should be used -> it's your decision ;)

> I do not know, I didn't find any guidelines on that. Any inputs @dbrgn @ubruhin?

I guess mostly we used "/" for negated functions, but we don't have a clear convention yet - thus I'm happy with both, "/" and "!" until we have conventions...

**Comment by dbrgn** [comment]
> It looks exactly the same as the DFN packages in the Base library - it's just one additional variant with a specific exposed pad size, isn't it?

Do we want to add all possible variants of exposed pad sizes to the standard library if they aren't standardized?

I'd be in favor of adding new variants with exposed pads, as long as we find that they are used in the industry by different manufacturers.

**Comment by ubruhin** [comment]
> Do we want to add all possible variants of exposed pad sizes to the standard library if they aren't standardized?

Depends on what you mean with "all possible variants" - if you mean "all actually existing variants", then yes, I'd add them to the Base library as long as (beside the non-standard exposed pad size) they are not special at all. I mean, the exposed pad size is contained in the IPC7351 conformant package name, so although it is not listed as a *standard* package, it's still a *generic* package IMHO.

Or in other words: What's the difference between "Microchip DFN50P200X300X90-8T175X145" and "Linear Technology DFN50P200X300X90-8T175X145"? :wink:

**Review by rnestler — APPROVED** [review]
LGTM. We can still decide later if we want to move the footprint out of this library.

**Comment by rnestler** [comment]
@ubruhin @HBadertscher Should we merge this as is?

**Comment by ubruhin** [comment]
If nobody complains, I could move the package to the base library to get this ready to merge.

**Comment by HBadertscher** [comment]
@rnestler @ubruhin Sorry for the delay from my side.

I added PRs to the librepcb-parts-generator and to the Base library. All UUIDs are still the same, so I think the only change required here is to remove the pkg, as I did now, right?

**Comment by rnestler** [comment]
> Sorry for the delay from my side.

@HBadertscher No hard feelings, this one was stale for quite a while :wink: I think we need to improve our library merging process in that regard.

> I added PRs to the librepcb-parts-generator and to the Base library. All UUIDs are still the same, so I think the only change required here is to remove the pkg, as I did now, right?

I guess so :slightly_smiling_face: Thanks for the effort!

**Comment by ubruhin** [comment]
Perfect, thanks a lot!

**Pull request merged**
